version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ../src/ui
    image: $USER_NAME/ui:logging
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    build: ../src/post-py
    image: $USER_NAME/post:logging
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    build: ../src/comment
    image: $USER_NAME/comment:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - reddit

  prometheus:
    build: ../monitoring/prometheus
    image: $USER_NAME/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - reddit

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - reddit

  black-box-exporter:
    build: ../monitoring/blackbox-exporter
    image: $USER_NAME/blackbox_exporter:latest
    ports:
      - '9115:9115'
    command: # Передаем доп параметры в командной строке
      - '--config.file=/config/blackbox.yml'
    networks:
      - reddit

#  cloudprober:
#    build: ../monitoring/cloudprober
#    image: $USER_NAME/cloudprober:latest
#    ports:
#      - '9313:9313'
#    networks:
#      - reddit

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - '9216:9216'
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      - reddit


volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
