apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 4Gi