apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim-dynamic-ssd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-ssd
  resources:
    requests:
      storage: 4Gi